---
title: "Mathematics with Julia"
output:
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty
---

```{r  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


About {data-navmenu="About"}
=====================================

Column {.tabset}
--------------------

### Mathematics with Julia

(<a href="http://juliaworkshop.github.io">Back to Main Page</a>)

#### Mathematics with Julia:

```{r child = "Maths_Programming_Julia.Rmd"}
```


```{r child = "Components/Rounding_Functions.Rmd"}
```

Trig Functions {data-navmenu="Modules"}
=====================================

Column {.tabset}
--------------------

```{r child = "Components/Trig_Functions.Rmd"}
```

Factorial Functions {data-navmenu="Modules"}
=====================================

Column {.tabset}
--------------------

```{r child = "Components/Factorial_Functions.Rmd"}
```

Complex Number {data-navmenu="Modules"}
=====================================

Column {.tabset}
--------------------

```{r child = "Components/Complex_Numbers.Rmd"}
```


Big Integers {data-navmenu="Modules"}
=====================================

Column {.tabset}
--------------------

```{r child = "Components/Big_Integers_Julia.Rmd"}
```

Project Euler {data-navmenu="Exercises"}
=====================================

Column {.tabset}
--------------------

```{r child = "Components/PRoject_Euler_Introduction.Rmd"}
```
