---
title: "Probability Distributions with Julia"
output:
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: minty
---

```{r  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


About {data-navmenu="About"}
=====================================

Column {.tabset}
--------------------

### Probability Distributions with Julia

(<a href="https://juliaworkshop.github.io">Back to Main Page</a>)

#### Probability Distributions with Julia:

Log-Normal Distribution {data-navmenu="Distributions"}
=====================================

Column {.tabset}
--------------------


```{r child = "Distributions/Log_Normal_Distribution_Julia.Rmd"}
```

Rayleigh Distribution {data-navmenu="Distributions"}
=====================================

Column {.tabset}
--------------------


```{r child = "Distributions/Rayleigh_Distribution_Julia.Rmd"}
```


```{r child = "Distributions/Rayleigh_Distribution_Julia_Example.Rmd"}
```

Cauchy Distribution {data-navmenu="Distributions"}
=====================================

Column {.tabset}
--------------------

### Cauchy Distribution
```{r child = "Distributions/Cauchy_Distribution_Julia.Rmd"}
```

```{r child = "Distributions/Cauchy_Distribution_Julia_Example.Rmd"}
```

Weibull Distribution {data-navmenu="Distributions"}
=====================================

Column {.tabset}
--------------------

### Weibull Distribution
```{r child = "Distributions/Weibull_Distribution_Julia.Rmd"}
```

```{r child = "Distributions/Weibull_Distribution_Julia_Example.Rmd"}
```



Beta Distribution {data-navmenu="Distributions"}
=====================================

Column {.tabset}
--------------------

### Beta Distributions
```{r child = "Distributions/Beta_Distribution_Julia.Rmd"}
```

Power Law Distributions {data-navmenu="Abvanced Topics"}
=====================================

Column {.tabset}
--------------------

### Power Law Distributions

```{r child = "Power_Law_Distributions_Julia.Rmd"}
```

Extreme Value Theory {data-navmenu="Abvanced Topics"}
=====================================

Column {.tabset}
--------------------

```{r child = "Extreme_Value_Theory_Julia.Rmd"}
```

Reliability Analysis {data-navmenu="Abvanced Topics"}
=====================================

Column {.tabset}
--------------------

```{r child = "Reliability_Analysis_Julia.Rmd"}
```

```{r child = "Weibull_Distribution_Example_Reliability.Rmd"}
```
