
<h1>Outlier Detection</h1>
One of the first steps towards obtaining a coherent analysis is the detection of outlaying observations. Although outliers are often considered as an error or noise, they may carry important information (see Mandelbrot/Taleb).

Detected outliers are candidates for aberrant data that may otherwise adversely lead to model misspecification, biased parameter estimation and incorrect results. It is therefore important to identify them prior to modelling and analysis.

Outlier detection methods have been suggested for numerous applications, such as credit card fraud detection, clinical trials, voting irregularity analysis, data cleansing, network intrusion, severe weather prediction, geographic information systems and athlete performance analysis.



<h2>Grubbs' Test</h2>
Grubbs' test is a formal hypothesis test for assessing whether or not a  data set contains an outlier.
This data set is univariate and approximately normal distributed. This test is designed for assessing one outlier only.  If more outliers are suspected, alternative tests, such as the Tietjen-Moore test, are recommended.

<h4>Hypotheses:</h4> Grubbs' test is defined for the hypothesis: 


Ho :  There are no outliers in the data set  
Ha :  There is exactly one outlier in the data set  

#### Outliers
<h3>Grubb's Test for Outliers</h3>
<pre><code>
library(outliers)
grubbs.test(X)
</code>
</pre>


#### Dixon Test for Outliers

<p>
</p><h4>Outliers on Boxplots</h4>
Boxplots can used to determine an outlie (we will refer to them as ``boxplot outliers")

<pre><code>
boxplot(X, horizontal = TRUE)
</code>
</pre>

To detect outliers in Julia using Grubbs' test, you'll need to use the `HypothesisTests` package, which provides statistical tests, including Grubbs' test. Here's how you can do it:

1. **Install and Load the Package:**

First, you'll need to install the `HypothesisTests` package if you haven't already:

```julia
using Pkg
Pkg.add("HypothesisTests")
```

Then, load the package:

```julia
using HypothesisTests
```

2. **Generate or Load Your Data:**

Let's assume you have a dataset:

```julia
data = [10.1, 12.3, 11.5, 11.8, 10.9, 12.2, 10.0, 29.5, 11.1, 10.6]  # Example data with a potential outlier
```

3. **Perform Grubbs' Test:**

To detect outliers, you can use the `GrubbsTest` function from the `HypothesisTests` package. This function tests the hypothesis that the maximum absolute deviation from the mean in the data is an outlier:

```julia
result = GrubbsTest(data)
```

4. **Check the Test Result:**

You can then check the result of the test to determine if there's an outlier:

```julia
println(result)
```

Here's the complete code:

```julia
using Pkg
Pkg.add("HypothesisTests")

using HypothesisTests

data = [10.1, 12.3, 11.5, 11.8, 10.9, 12.2, 10.0, 29.5, 11.1, 10.6]  # Example data with a potential outlier

result = GrubbsTest(data)

println(result)
```

If the p-value is small (typically less than 0.05), you can reject the null hypothesis and conclude that there's an outlier in your data. The test provides both the test statistic and the p-value, which help in determining the presence of an outlier.

